### ISSUE TITLE
怎么设置隐藏标题栏，让用户自定义，并且可以支持拖动窗口

### ISSUE THREAD

**Issue by Eddie-sk** [Kingtous/rustdesk_desktop_multi_window#1]

**Comment by Kingtous** [comment]
目前rustdesk这边实践发现Multi window与bitsojo这些库有冲突。bitsojo是可以自定义的

**Comment by Eddie-sk** [comment]
主窗口可以用bitsojo来设置屏幕，弹出来的新窗口没办法来自定义界面了吧

**Comment by Kingtous** [comment]
是的，其他库要额外适配新窗口逻辑。

**Comment by Kingtous** [comment]
近期对multi window库进行了扩充，也可以进行自定义标题栏
