### ISSUE TITLE
在linux上编译失败

### ISSUE THREAD

**Issue by 1056824847** [Kingtous/rustdesk_desktop_multi_window#19]
<img width="1435" alt="image" src="https://github.com/Kingtous/rustdesk_desktop_multi_window/assets/44287872/3b927cde-790f-4fe1-9b7a-ac12b9b5d2c0">
当前系统是银河麒麟v10系统，linux内核为4.1的，目前测试在linux内核5.0上是可以编译通过的

**Comment by Kingtous** [comment]
看上去是你gcc环境问题
