### ISSUE TITLE
创建新的窗口的时候会崩溃

### ISSUE THREAD

**Issue by 1056824847** [Kingtous/rustdesk_desktop_multi_window#2]
在windows 11 上是会奔溃的，在mac上就正常，还有想问下如何让新的窗口出现在副屏上，别显示在主屏幕上

**Comment by Kingtous** [comment]
win需要使用 flutter 3.0.5版本

**Comment by sliwei** [comment]
> win需要使用 flutter 3.0.5版本

亲测，开发模式依然崩溃，打包成应用就不会崩溃了

![image](https://user-images.githubusercontent.com/21306252/192188643-6e45b2c8-791d-417b-a415-7259c57dc5eb.png)

**Comment by Kingtous** [comment]
我这边debug和release都不会崩溃，很奇怪

**Comment by sliwei** [comment]
请教一下，可以在子窗口中使用window_manager吗？主窗口正常，子窗口提示「No implementation found for method setTitleBarStyle on channel window_manager」

**Comment by Kingtous** [comment]
> 请教一下，可以在子窗口中使用window_manager吗？主窗口正常，子窗口提示「No implementation found for method setTitleBarStyle on channel window_manager」

不可以，并且要注意不要二次注册window_manager，详见https://github.com/Kingtous/rustdesk_window_manager/commit/247818257b4b37f78bebea1719cee765282b3079
为了解决这个问题，Rustdesk将部分window_manager的函数迁移至了多窗口环境，详见本仓库。

**Comment by sliwei** [comment]
> > 请教一下，可以在子窗口中使用window_manager吗？主窗口正常，子提示“No implementation found for method setTitleBarStyle on channel window_manager”
> 
> 不可以，而且要注意不要二次注册window_manager，查看[Kingtous/rustdesk_window_manager@ 2478182 为](https://github.com/Kingtous/rustdesk_window_manager/commit/247818257b4b37f78bebea1719cee765282b3079) 解决这个问题，Rustdesk将部分window_manager的函数迁移至多个窗口，查看本库。

感谢告知，很高兴你在做迁移工作，你是打算将window_manager的大部分函数迁移到Rustdesk吗？（带多窗口的window_manager将在桌面端很实用）

**Comment by Kingtous** [comment]
> > > 请教一下，可以在子窗口中使用window_manager吗？主窗口正常，子提示“No implementation found for method setTitleBarStyle on channel window_manager”
> > 
> > 
> > 不可以，而且要注意不要二次注册window_manager，查看[Kingtous/rustdesk_window_manager@ 2478182 为](https://github.com/Kingtous/rustdesk_window_manager/commit/247818257b4b37f78bebea1719cee765282b3079) 解决这个问题，Rustdesk将部分window_manager的函数迁移至多个窗口，查看本库。
> 
> 感谢告知，很高兴你在做迁移工作，你是打算将window_manager的大部分函数迁移到Rustdesk吗？（带多窗口的window_manager将在桌面端很实用）

目前已经完成了一些常用的函数，详见https://github.com/Kingtous/rustdesk_desktop_multi_window/blob/master/lib/src/window_controller.dart
目前我们用到了这些

**Comment by sliwei** [comment]
> > > > 请教一下，可以在子窗口中使用window_manager吗？主窗口正常，子提示“No implementation found for method setTitleBarStyle on channel window_manager”
> > > 
> > > 
> > > 不可以，而且要注意不要二次注册window_manager，查看[Kingtous/rustdesk_window_manager@ 2478182 为](https://github.com/Kingtous/rustdesk_window_manager/commit/247818257b4b37f78bebea1719cee765282b3079) 解决这个问题，Rustdesk将部分window_manager的函数迁移至多个窗口，查看本库。
> > 
> > 
> > 感谢告知，很高兴你在做迁移工作，你是打算将window_manager的大部分函数迁移到Rustdesk吗？（带多窗口的window_manager将在桌面端很实用）
> 
> 目前已经完成了一些常用的函数，详见https://github.com/Kingtous/rustdesk_desktop_multi_window/blob/master/lib/src/window_controller.dart 目前我们用到了这些

弱弱问句，有实现窗口置顶功能的计划吗？

**Comment by Kingtous** [comment]
> > > > > 请教一下，可以在子窗口中使用window_manager吗？主窗口正常，子提示“No implementation found for method setTitleBarStyle on channel window_manager”
> > > > 
> > > > 
> > > > 不可以，而且要注意不要二次注册window_manager，查看[Kingtous/rustdesk_window_manager@ 2478182 为](https://github.com/Kingtous/rustdesk_window_manager/commit/247818257b4b37f78bebea1719cee765282b3079) 解决这个问题，Rustdesk将部分window_manager的函数迁移至多个窗口，查看本库。
> > > 
> > > 
> > > 感谢告知，很高兴你在做迁移工作，你是打算将window_manager的大部分函数迁移到Rustdesk吗？（带多窗口的window_manager将在桌面端很实用）
> > 
> > 
> > 目前已经完成了一些常用的函数，详见https://github.com/Kingtous/rustdesk_desktop_multi_window/blob/master/lib/src/window_controller.dart 目前我们用到了这些
> 
> 弱弱问句，有实现窗口置顶功能的计划吗？

目前没有，有兴趣提PR吗

**Comment by sliwei** [comment]
> 

入门级flutter，mac和win原生也不会，有心无力了，哈哈哈，我先学习一下

**Comment by sliwei** [comment]
> > > > > > 请教一下，可以在子窗口中使用window_manager吗？主窗口正常，子提示“No implementation found for method setTitleBarStyle on channel window_manager”
> > > > > 
> > > > > 
> > > > > 不可以，而且要注意不要二次注册window_manager，查看[Kingtous/rustdesk_window_manager@ 2478182 为](https://github.com/Kingtous/rustdesk_window_manager/commit/247818257b4b37f78bebea1719cee765282b3079) 解决这个问题，Rustdesk将部分window_manager的函数迁移至多个窗口，查看本库。
> > > > 
> > > > 
> > > > 感谢告知，很高兴你在做迁移工作，你是打算将window_manager的大部分函数迁移到Rustdesk吗？（带多窗口的window_manager将在桌面端很实用）
> > > 
> > > 
> > > 目前已经完成了一些常用的函数，详见https://github.com/Kingtous/rustdesk_desktop_multi_window/blob/master/lib/src/window_controller.dart 目前我们用到了这些
> > 
> > 
> > 弱弱问句，有实现窗口置顶功能的计划吗？
> 
> 目前没有，有兴趣提PR吗

入门级flutter，mac和win原生也不会，有心无力了，哈哈哈，我先学习一下

**Comment by zkteco-home** [comment]
> win需要使用 flutter 3.0.5版本

只是在此分享下使用的情况，我使用flutter 3.3.6 stable版，win11测试新窗口崩溃，希望能支持新版flutter

**Comment by Kingtous** [comment]
flutter master分支已修复崩溃问题

**Comment by zkteco-home** [comment]
> flutter master分支已修复崩溃问题
我使用flutter 3.3.8版编译后，点击Connect按钮后还是崩溃，也许和以上反馈的不是一个问题？

[2022-11-11T05:42:59Z INFO  librustdesk::ui_session_interface] starting global grab keyboard
flutter: [MultiWindowHandler] active window changed: [0]
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
The Flutter DevTools debugger and profiler on Windows is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:49694/BDVn_MMyCX4=/
flutter: fetch id again at 0:id:1482065033
flutter: [MultiWindowHandler] active window changed: []
../../flutter/shell/platform/embedder/embedder.cc (2244): 'FlutterEngineOnVsync' returned 'kInternalInconsistency'. Could not notify the running engine instance of a Vsync event.
Lost connection to device.


![image](https://user-images.githubusercontent.com/66519168/201271850-6d5cc19c-c824-4b46-a3fe-06f44d8e7aa3.png)

**Comment by zkteco-home** [comment]
@Kingtous 我了解你也是RustDesk成员之一，有个问题想请教下你，文件传输功能操作显示都100%传输了，但对方电脑的文件是0，知道为什么吗

**Comment by Kingtous** [comment]
> @Kingtous 我了解你也是RustDesk成员之一，有个问题想请教下你，文件传输功能操作显示都100%传输了，但对方电脑的文件是0，知道为什么吗

可以到主仓库发个issue 提供一下环境

**Comment by zkteco-home** [comment]
> 

主仓库认为是编译问题就给关闭了，实际上我知道如何编译，我起初用flutter 3.3.6 3.3.8编译都是新窗口崩溃，后改用3.0.5了。
我的环境是win11, rustdesk 最新代码 1.2.0，flutter编译的，我不用flutter编译的也是同一个问题，按说很多人在用，不该有这个问题
