### ISSUE TITLE
我创建新的窗口，程序就崩溃了，windows平台

### ISSUE THREAD

**Issue by denghanhao** [Kingtous/rustdesk_desktop_multi_window#4]
我创建新的窗口，程序就崩溃了，windows平台

**Comment by denghanhao** [comment]
我重新通过git链接添加了依赖，但是运行就报错：
严重性 错误	C1083	无法打开包括文件: “url_launcher_windows/url_launcher_windows.h”: No such file or directory	desktop_multi_window_plugin

flutter版本3.3，平台是win10

**Comment by xiyionxiong** [comment]
需要把url_launcher 依赖加入到  pubspec.yaml 中 
同时将 window_size 加入到pubspec.yaml中

**Comment by Kingtous** [comment]
> 我重新通过git链接添加了依赖，但是运行就报错： 严重性 错误 C1083 无法打开包括文件: “url_launcher_windows/url_launcher_windows.h”: No such file or directory desktop_multi_window_plugin
> 
> flutter版本3.3，平台是win10

另外需要flutter 3.0.5版本或者flutter master版本
